env:
  CI: true
jobs:
  test:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{github.head_ref}}
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - run: bash ./scripts/setup.sh
      - name: Run lint and format check
        run: bash ./scripts/lint.sh
      - name: Run unit tests
        run: bash ./scripts/tests/unit.sh
name: Verify PR

on: pull_request